CREATE TABLE TODO (
	ID bigint GENERATED BY DEFAULT AS IDENTITY,
	DESCRIPTION varchar(1000) not null
);

create sequence todo_sequence start with 1 increment by 1;

INSERT INTO TODO (DESCRIPTION) VALUES ('walk the dog');
INSERT INTO TODO (DESCRIPTION) VALUES ('buy food');
INSERT INTO TODO (DESCRIPTION) VALUES ('do workout');
INSERT INTO TODO (DESCRIPTION) VALUES ('go to job');